export const HOME = 'Shoping';
export const CART = 'Sepetim';
export const CATEGORIES = 'Kategoriler';
export const PROFILE = 'Profil';
export const FAVOURITE = 'Favoriler';
export const TAB = 'TabNavigator'
export const PRODUCTSLIST = 'Ürün Listesi'
export const PRODUCTDETAIL = 'Ürün Detayı'
export const LOGIN = 'Login'
export const CHECKOUT = 'Check Out'
